services:
  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    volumes:
      - .:/vault
    command: ["run", "--config", "/vault/scrapem.yaml"]
    restart: "no"

  scheduler:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    volumes:
      - .:/vault
    command: ["watch", "--config", "/vault/scrapem.yaml"]
    restart: unless-stopped
